name: Enforce Package Dependency Version
description: Enforce a package version for a dependency or dev-dependency.
branding:
  icon: lock
  color: yellow

runs:
  using: "node16"
  main: "dist/index.js"

inputs:
  package:
    description: "The name of the dependency to check."
    required: true
  directory:
    description: "Directory where your `package.json` can be found.  Defaults to to `env.GITHUB_WORKSPACE`."
    required: false
  range:
    description: "A semver range, eg. '^1.0.0', '1.0.0', '>=1.x', etc.."
    required: true
  version_prerelease:
    description: >-
      An optional prerelease target.  Defaults to false.
       - `false` requires there is no prerelease.
       - `true` allows a prerelease—but it is not required! `1.2.3-prerelease` and `1.2.3` are both valid
       - `'prerelease'` means it must match that prerelease.
       - `'prerelease.#'` means it must match that prerelease and identifier.
    default: false
    required: false
  allow_multiple_versions:
    description: >-
      Whether or not we allow multiple versions to be resolved, eg. you may have Typescript at `^4.2.0` in your codebase, but another package points to `3.x`.
       - `false` means this should only ever resolve to a single version (and that should match our range)
       - `true` allows all versions… NOTE: we only look at the first resolved version, assuming this is your version.
    default: false
    required: false

outputs:
  resolved_version:
    description: "The resolved version of that dependency, eg. in `yarn.lock`"
  target_version:
    description: "The target version of that dependency, eg. version in `package.json`"
